### ISSUE TITLE
IndexError at 'knn_classifier.py'

### ISSUE THREAD

**Issue by utkudmir** [ahmetozlu/color_recognition#3]
```
training data is ready, classifier is loading...
Traceback (most recent call last):
  File ".\src\color_classification_image.py", line 32, in <module>
    prediction = knn_classifier.main('training.data', 'test.data')
  File "...\color_recognition-master\color_recognition-master\src\color_recognition_api\knn_classifier.py", line 87, in main
    return classifier_prediction[0])
IndexError: list index out of range
```

**Comment by KeramKeram** [comment]
Het @utkudmir  I know it's propably to late but problem is lack of black_cat.jpg in folder.

**Comment by ahmetozlu** [comment]
@utkudmir could you share your test image, please? The error must be caused by your input file structure.
